apiVersion: v1
kind: Service
metadata:
  name: mahaapp-svc
  labels:
    app: mahaapp
    version: 2.7.01
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: mahaapp
    version: 2.7.01