apiVersion: v1
kind: ReplicationController
metadata:
  name: mahaapp-rc
spec:
  replicas: 2
  selector:
    app: mahaapp
    version: 2.7.02
  template:
    metadata:
      labels:
        app: mahaapp
        version: 2.7.02
    spec:
      containers:
      - name: mahajavaapp-container
        image: maha4iac/myonlinebooking:2
        ports:
        - containerPort: 8080