apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahajavaapp-deploy
  labels:
    app: mahajavaapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mahajavaapp
  template:
    metadata:
      labels:
        app: mahajavaapp
    spec:
      containers:
      - name: mahajavaapp-container
        image: maha4iac/myonlinebooking:1
        ports:
        - containerPort: 8080