apiVersion: v1
kind: Service
metadata:
  name: mahajavaapp-svc
  labels:
    app: mahajavaapp    
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    protocol: TCP
  selector:
    app: mahajavaapp